### PR TITLE
Adding cor_test function

### LINKED ISSUE #22: Add cor_test() function
Adding Correlation Testing function.

Current version in [MoffittFunctions](https://github.com/wfulp/MoffittFunctions/blob/master/R/statistical_tests_and_estimates.R).

Older version in [VISCfunctions_Galactica](https://github.com/FredHutch/VISCfunctions_Galactica/blob/master/R/statistical_tests_and_estimates.R) (called `spearman_test_VISC()`)

### PR DESCRIPTION
**Pull request by wfulp**
closes #22 

`cor_test` is wrapper for cor.test function, except if spearman is selected and there are ties in at least one variable, in which case this is a wrapper for `coin::spearman_test` with approximate method. This is the go-to function for appropriate Spearman testing, because if there are no ties in either variable you can use the exact method through `cor.test`, but if there are ties the best method is `coin::spearman_test` with approximate method (`cor.test` will change it to asymptotic t approximation method if ties)

I also cleaned up the .Rbuildignore file and updated man files with new Roxygen version.

```
set.seed(5432322)
x <- rnorm(20,0,3)
y <- x + rnorm(20,0,5)
cor_test(x,y, method = 'pearson')
cor_test(x,y, method = 'kendall')
cor_test(x,y, method = 'spearman')
# Adding ties
cor_test(c(x,x), c(y,y), method = 'spearman',
         seed = 1, B = 10000, verbose = TRUE)
```

Thanks for offering to review @rkuttnerFHCR. Our code review documentation for your reference is [here](https://github.com/FredHutch/VISC-Documentation/blob/master/Programming/Package-Development/README.md). @monicagerber has offered to be a secondary reviewer.

### CODE REVIEW

**Comment by wfulp** [comment]
> @wfulp , this looks great! I love your effort to keep `cor_test` as similar to `stats::cor.test` as possible.
> The only thing I noticed was the function `cor_test()` changes the global environment with `set.seed()`. Changing the global environment of the user can lead to unexpected behavior, such as breaking the randomness if nested in a larger simulation. I'd recommend using `withr::with_seed()` or a more crude example can be followed [here](https://stackoverflow.com/questions/56191862/where-do-i-specify-random-seed-for-tests-in-r-package).

Great point. I added `withr::with_seed()` to the cor_test function. Also add a test case making sure random seed is kept.

**Comment by celiaeddy** [comment]
looks good and runs as expected.

a few documentation suggestions:

```
#' This function is a wrapper for \code{stats::cor.test function}, except if \code{method = "spearman"} 
#' is selected and there are ties in at least one variable, in which case this is a wrapper for
#'   \code{coin::spearman_test} employing the approximate method.
```

```
#' @param method a character string indicating which correlation coefficient
#'   is to be used for the test. One of "pearson", "kendall", or "spearman",
#'   can be abbreviated to "p", "k", or "s".
```

Also update the following to reflect the `coin` package parameter change from `B` to `nresample`
1. the function itself:

```
cor_test <- function(x,
                     y,
                     method = c("pearson", "kendall", "spearman"),
                     seed = 68954857,
                     nresample = 10000,
                     exact = TRUE,
                     verbose = FALSE){
  method <- match.arg(method)
  .check_numeric_input(x)
  .check_numeric_input(y)
  if (method == "spearman") {
    .check_numeric_input(seed,
                         lower_bound = -2^30,
                         upper_bound = 2^30,
                         scalar = TRUE,
                         whole_num = TRUE)
    .check_numeric_input(nresample,
                         lower_bound = 1,
                         upper_bound = 2^20,
                         scalar = TRUE,
                         whole_num = TRUE)
  }

  rm_na_and_check_output <- .rm_na_and_check(x,
                                             y,
                                             x_type = 'continuous',
                                             y_type = 'continuous',
                                             verbose = verbose)
  if (is.data.frame(rm_na_and_check_output)) {
    data_here <- rm_na_and_check_output
  } else {
    return(rm_na_and_check_output)
  }

  # if spearman with ties calling coin::spearman_test, otherwise cor.test
  if (method == "spearman" &
      exact == TRUE &
      (any(duplicated(data_here$x)) |
       any(duplicated(data_here$y)))) {
    if (verbose) message('Either "x" or "y" has ties, so using approximate method.')
    withr::with_seed(seed = seed,
                     as.double(coin::pvalue(
                       coin::spearman_test(x~y,
                                           data = data_here,
                                           distribution = coin::approximate(nresample)
                       )))

                     )
  } else {
    as.double(stats::cor.test(data_here$x,
                       data_here$y,
                       method = method,
                       exact = exact)$p.value)
  }
}
```

2. the parameter:

```
#' @param nresample a positive integer, the number of Monte Carlo replicates used 
#' for the computation of the approximative reference distribution. Defaults to 10000.
```


3. The dependency (version of `coin` with param = `nresample`)

**Comment by seajane** [comment]
Looks good and runs mostly as expected. 

Unexpected results:
 - Adding a logical value (TRUE, FALSE) to a vector produces a result
 - Perfect correlation (x=y) and anti-correlation (x = -y) should be 1, but returns a value of 0.
 - Short vector issue in Pearson's Method:
    - If 'x' and 'y' are each length = 1, this is the error, ""x" only has 1 distinct value when considering non-missing values of "y", so p=1 returned".  (used x = 1, y =7)
    - If both 'x' and 'y' are each length = 2, then there is no error, 
    - shouldn't the limit be ~4 and not 1? 
 
Some suggestions: 
- cor_test doesn't allow further arguments to be passed from cor.test or spearman_test.  Useful parameters like 'conf.level', and 'alternative' are missing from cor.test, and 'subset' is missing from both. 'formula' is in both and would be difficult to apply as it is used differently in each method.

 - The help page is lacking a "Details" section that talks about the methods.  It would be nice to have to help one remember that Pearson assumes normality and linearity and Kendall and Spearman are non-parametric.

Conditions checked:
-[ ] vector contains 'NA' and produces a result
-[ ] data with a character fails to run
-[ ] binomial data produces a result
-[ ] data of different lengths fails to run
-[ ] non-parametric data - as expected but a caution with non-parametric tests
s= 0.8820669, p = 0.000240919, k =0.8842872
image

**Comment by celiaeddy** [comment]
> * Perfect correlation (x=y) and anti-correlation (x = -y) should be 1, but returns a value of 0.

doesn't the function return the p-value? not the correlation estimate?

**Comment by seajane** [comment]
> 
> 
> > * Perfect correlation (x=y) and anti-correlation (x = -y) should be 1, but returns a value of 0.
> 
> doesn't the function return the p-value? not the correlation estimate?

Ah yes, was used to all the values of cor.test, not just p-value.  Will adjust my comment.

**Comment by celiaeddy** [comment]
> > > * Perfect correlation (x=y) and anti-correlation (x = -y) should be 1, but returns a value of 0.
> > 
> > 
> > doesn't the function return the p-value? not the correlation estimate?
> 
> Ah yes, was used to all the values of cor.test, not just p-value. Will adjust my comment.

I wanted to double check because I tried the same thing and almost commented the same thing!

**Comment by wfulp** [comment]
> Useful parameters like 'conf.level', and 'alternative' are missing from cor.test

I didn't even know `cor.test` had an alternative param. I've never done a one-sided cor test before. 

I can add `...` so the user can pass params through to `cor.test` or `spearman_test`

**Comment by wfulp** [comment]
I think we can restrict it to 3 non-missing pairs. Otherwise error message

**Pull request merged**
